### ISSUE TITLE
这是怎么用的？没弄明白，访问不到

### ISSUE THREAD

**Issue by lbx-ai** [FloatTech/ZeroBot-Plugin#78]
已经自己编译，将注释打开了，但是不知道怎么访问前端页面

**Comment by guohuiyuan** [comment]
> 已经自己编译，将注释打开了，但是不知道怎么访问前端页面

打开http://localhost:3000

**Comment by lbx-ai** [comment]
![image](https://user-images.githubusercontent.com/44740855/142730398-d866f569-3995-4985-9d50-3da6bb801918.png)
监听不应该是127.0.0.1，这样只能在本地访问，需要把这个去掉才能在远程查看

**Comment by lbx-ai** [comment]
而且我这个ui里面没数据，不知道是怎么回事

**Comment by guohuiyuan** [comment]
问题最新代码，已经不是这样写了，还是远程访问不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月20日(星期六) 晚上10:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FloatTech/ZeroBot-Plugin] 这是怎么用的？没弄明白，访问不到 (Issue #78)





 

 监听不应该是127.0.0.1，这样只能在本地访问，需要把这个去掉才能在远程查看
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lbx-ai** [comment]
> 

把127.0.0.1去掉过后，我就可以访问了，只是里面没有数据

**Comment by fumiama** [comment]
最新提交添加了新功能，可以自定义监听地址了。
